feat: Make OIDC HTTP request timeout configurable
famedly/uia-proxy pull request #213
Opened 2023-10-26 22:49 UTC by pi-314

- Remove secrets disclosure in log
- Make OIDC HTTP request timeout configurable

2023-10-27 06:51 UTC, emgrav approved these changes
Looks great! I have two suggestions, but they're both very minor so I will approve the PR nonetheless and let you decide whether to merge now or incorporate them.

2023-10-27 06:51 UTC, emgrav commented on config.sample.yaml
> +            # HTTP request timeout in ms. (defaults to 20000)
While mentioning a default implies that it is, I think Infra would appreciate if it was explicitly described as optional.

2023-10-27 06:51 UTC, emgrav commented on src/stages/com.famedly.login.sso/openid.ts
> +			} else {
Personally, I think the program should simply fail to start if a value has been provided but it's incorrect, rather than falling back to a default. The user intent is clearly to change the value, and not succeeding in this should fail in a way the user is sure to notice.

That said, I also don't think it's *that* important, especially for this component right now, so if you would prefer to just keep it like this that's also fine.

2023-10-27 07:26 UTC, AgathaSorceress commented on src/stagehandler.ts
> +							// **********************************************************************************************************************
I think it might be better to just completely remove these lines

2023-10-27 07:26 UTC, AgathaSorceress commented on src/stagehandler.ts
> +
Same here

2023-10-27 08:23 UTC, pi-314 commented on config.sample.yaml
> +            # HTTP request timeout in ms. (defaults to 20000)
I'll improve the description.

2023-10-27 09:36 UTC, pi-314 commented on src/stagehandler.ts
> +
Well, that lines was crucial to figure out the cause of the initial bug. That's why I decided to keep they commented out, just for the case if somebody else will have to do the same. But it would be also not a big deal to just throw it away.

2023-10-27 10:44 UTC, pi-314 commented on src/stages/com.famedly.login.sso/openid.ts
> +			} else {
I completely agree! It was also my first approach, just according to the "fail fast and fail safe" principle. But then I had doubts about whether it would be a good idea to introduce a whole new "error type" because of this one small change. But if you also think it's right, I'll be happy to change it that way.

2023-10-27 11:38 UTC, AgathaSorceress commented on src/stagehandler.ts
> +
If the lines are kept, I think the comment can be a lot cleaner
```suggestion
			// The following lines should only be uncommented for debugging, since the reply may include sensitive data.
			//
			// // eslint-disable-next-line no-magic-numbers
			// this.log.silly(`Reply=\n${JSON.stringify(reply, null, 2)}, STATUS CODE: ${STATUS_UNAUTHORIZED}`);
```

2023-10-27 13:22 UTC, pi-314 commented on src/stagehandler.ts
> +
Too late, I just threw them away 😃

2023-10-27 13:33 UTC, emgrav commented
Looks great! Just one more thought, we could probably incorporate the version bump in this PR as well? No need for that to be a separate PR

2023-10-27 14:29 UTC, pi-314 commented
@emgrav Done.

2023-10-30 07:18 UTC, emgrav approved these changes
LGTM

2023-11-01 06:16 UTC, emgrav requested changes
Looks fantastic, really thorough work! I saw a couple of typos in comments but otherwise LGTM!

2023-11-01 06:16 UTC, emgrav commented on test/passwordproviders/test_passwordprovider_ldap.ts
> +/** Storage for the callbacks, which our CUT should register by the real ldap.Client for 'conectError' event. */
```suggestion
/** Storage for the callbacks, which our CUT should register by the real ldap.Client for 'connectError' event. */
```

2023-11-01 06:16 UTC, emgrav commented on test/passwordproviders/test_passwordprovider_ldap.ts
> +/** Storage for the callbacks, which our CUT should register by the real ldap.Client for 'conectError' event. */
What's a CUT?

2023-11-01 06:16 UTC, emgrav commented on test/passwordproviders/test_passwordprovider_ldap.ts
> +function triggerAllErrors(onInvocation: () => void): number {
There are two doc comments for this function, is this intentional?

2023-11-01 06:16 UTC, emgrav commented on test/passwordproviders/test_passwordprovider_ldap.ts
> +	// Note that if no listener are registered, nothing will be triggered.
```suggestion
	// Note that if no listeners are registered, nothing will be triggered.
```

2023-11-01 06:16 UTC, emgrav commented on test/passwordproviders/test_passwordprovider_ldap.ts
> +			log.verbose(`riggerAllErrors() No callback found, nothing to call`);
```suggestion
			log.verbose(`triggerAllErrors() No callback found, nothing to call`);
```

2023-11-01 06:16 UTC, emgrav commented on README.md
> +This will give you the possibility to run any test or testsuit (A) and see the results directly in the source (B). Corresponding settings are in (1,2 and 3). If you need to finetune some deep Mocha s
```suggestion
This will give you the possibility to run any test or test suite (A) and see the results directly in the source (B). Corresponding settings are in (1, 2 and 3). If you need to fine-tune some deep Mocha setting by monkey patching, do it in `.mocharc.js` (4).
```

2023-11-01 06:16 UTC, emgrav commented on README.md
> +With the run configuration '**Mocha tests**' (provided in `launch.json`) you can also start debugging session (C) for both of the project code and tests.
```suggestion
With the run configuration '**Mocha tests**' (provided in `launch.json`) you can also start debugging session (C) for both the project code and tests.
```

2023-11-01 09:18 UTC, pi-314 commented on test/passwordproviders/test_passwordprovider_ldap.ts
> +function triggerAllErrors(onInvocation: () => void): number {
Oh no... 🤦🏻 This is because of working till 4 A.M.

2023-11-01 09:21 UTC, pi-314 commented on test/passwordproviders/test_passwordprovider_ldap.ts
> +/** Storage for the callbacks, which our CUT should register by the real ldap.Client for 'conectError' event. */
Class Under Test (if we can call that mess a class).

2023-11-01 14:26 UTC, emgrav approved these changes
LGTM!

2023-11-01 16:19 UTC, merged